### ISSUE TITLE
Need Help...I'm new to building rom

### ISSUE THREAD

**Issue by Mrick343** [LeCmnGend/How_to_build_ROM#3]
""02. Setup PATH (should install ccache in part 3 first)
Use notepad++ or some editor tool, open /root/.bashrc and paste this to the end:

$ 
export USE_CCACHE=1
export CCACHE_CPP2=true
export CCACHE_COMPILERTYPE=clang
export CCACHE_EXEC=/usr/local/bin/ccache
export CCACHE_MAXSIZE=30G
export CCACHE_DIR=/mnt/e/.ccache
export CCACHE_BASEDIR=/mnt/e/.ccache
export CCACHE_NOHASHDIR=1
export CCACHE_UMASK=002
export CCACHE_TEMPDIR=$CCACHE_BASEDIR/tmp
export CCACHE_LIMIT_MULTIPLE=0.97
export CCACHE_SLOPPINESS=file_macro,time_macros,include_file_mtime,include_file_ctime,file_stat_matches
export CCACHE_COMPRESS=true
export CCACHE_COMPRESSLEVEL=1
export ANDROID_SDK_ROOT=/root/Android/Sdk
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
export ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx11G"

export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/cmdline-tools/tools/bin
export PATH=/root/bin:$PATH
export PATH=$JAVA_HOME/bin:$PATH

#HOST TOOLCHAIN 
export PATH=~/tc/proton/clang-16/bin:$PATH
export TC_DIR="/root/tc/proton/clang-16"
export CC="clang"
export CXX="clang++"
export THINLTO_CACHE_DIR="/mnt/e/.ccache/ltocache/"
export KBUILD_COMPILER_STRING="$($TC_DIR/bin/clang --version | head -n 1 | perl -pe 's/\((?:http|git).*?\)//gs' | sed -e 's/  */ /g' -e 's/[[:space:]]*$//' -e 's/^.*clang/clang/')"
export STRIP="$TC_DIR/bin/$(echo "$(find "$TC_DIR/bin" -type f -name "aarch64-*-gcc")" | awk -F '/' '{print $NF}' | sed -e 's/gcc/strip/')"
Then run:

$ source ~/.bashrc""

when i run "source ~/.bashrc" after pasting the code. the terminal shows error like this
![Screenshot_20230122_160208](https://user-images.githubusercontent.com/85066116/213911466-32ca5bfc-25e9-489f-af30-998f9f2687f1.png)

**Comment by LeCmnGend** [comment]
try to run sudo apt update
then sudo apt upgrade

**Comment by LeCmnGend** [comment]
It should be done?
