### ISSUE TITLE
Error in installing Proton Clang 17

### ISSUE THREAD

**Issue by Aeoniixx** [LeCmnGend/How_to_build_ROM#4]
I was on part 02 and as per the 01 step i followed the commands but while running command bash b-pre.sh I got this error
![Screenshot 2023-07-16 194434 (2)](https://github.com/LeCmnGend/How_to_build_ROM/assets/138367906/40036f0f-48c3-4bec-b254-2b4d2d476d93)
Please help me

**Comment by LeCmnGend** [comment]
last week git lab has some suspended time, 
you can try to clone clang-17 by using:
$git clone https://gitlab.com/LeCmnGend/proton-clang -b clang-17 --depth=1 /home/abhi/tc/proton/clang-17

**Comment by Aeoniixx** [comment]
Sir where are this locations. Please tell me I can't find.
Z:\root and E: \ .ccache\ccache.conf

![Screenshot_20230818-072745_Chrome](https://github.com/LeCmnGend/How_to_build_ROM/assets/138367906/93445d1d-0597-4dc4-9478-2101e0677871)
![Screenshot_20230818-072706_Chrome](https://github.com/LeCmnGend/How_to_build_ROM/assets/138367906/fbd8f954-2272-410a-9329-7e019fd4f5d8)

**Comment by LeCmnGend** [comment]
\\wsl.localhost\Ubuntu
here is the full path of Z device (z just a shortcut)

**Comment by LeCmnGend** [comment]
![image](https://github.com/LeCmnGend/How_to_build_ROM/assets/46700663/124a5587-11cf-4fa9-ae17-3774b8688b73)
paste in here and you can access ubuntu folder

**Comment by Aeoniixx** [comment]
And where is this 
E: \ .ccache\ccache.conf

**Comment by Aeoniixx** [comment]
> And where is this E: \ .ccache\ccache.conf

Please tell me sir

**Comment by LeCmnGend** [comment]
Just create one

Vào 8:10, Th 7, 19 thg 8, 2023 Abhi ***@***.***> đã viết:

**Comment by Aeoniixx** [comment]
what size should i enter here ?
![s](https://github.com/LeCmnGend/How_to_build_ROM/assets/138367906/bb7c0e5a-9c2f-4b0b-8b5d-c7c5db1aa2fd)

**Comment by LeCmnGend** [comment]
skip these steps, wsl2 is updated now.
/*-----------------------------------------------
   Thân mến                                     //

* Nguyễn Hoàng Nam              //
* 0947 709 305                       //
* ***@***.***   //

* Telegram: @iambigN            //

*/-----------------------------------------------



Vào Th 2, 21 thg 8, 2023 vào lúc 12:27 Abhi ***@***.***> đã
viết:

**Comment by LeCmnGend** [comment]
Have you fix this?
